language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install --upgrade setuptools"
install: "pip install astropy astroquery"
# command to run tests
script: pytest
